# Generated by Django 6.1 on 2026-08-29 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_autor', models.CharField(help_text='Nombre completo o identificador del autor', max_length=150, verbose_name='Nombre del Autor')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_editorial', models.CharField(help_text='Nombre de la casa editorial', max_length=150, verbose_name='Nombre de la Editorial')),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
            },
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(help_text='Nombres de pila del lector (campo atómico)', max_length=100, verbose_name='Nombres')),
                ('apellido_p', models.CharField(help_text='Primer apellido del lector (campo atómico)', max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_m', models.CharField(help_text='Segundo apellido del lector (campo atómico)', max_length=100, verbose_name='Apellido Materno')),
                ('is_active', models.BooleanField(default=True, help_text='Bandera para borrado lógico. True = Activo, False = Inactivo', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Lector',
                'verbose_name_plural': 'Lectores',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título de la obra literaria', max_length=200, verbose_name='Título del Libro')),
                ('autores', models.ManyToManyField(help_text='Autores asociados al libro (relación N:M)', related_name='libros', to='api.autor', verbose_name='Autores')),
                ('editoriales', models.ManyToManyField(help_text='Editoriales asociadas al libro (relación N:M)', related_name='libros', to='api.editorial', verbose_name='Editoriales')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_dev', models.DateField(help_text='Fecha comprometida para la devolución del libro', verbose_name='Fecha de Devolución')),
                ('devuelto', models.BooleanField(default=False, help_text='Indica si el libro ya fue devuelto a la biblioteca (False = En préstamo activo)', verbose_name='Devuelto')),
                ('lector', models.ForeignKey(help_text='Referencia al lector que tiene el préstamo (FK)', on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='api.lector', verbose_name='Lector')),
                ('libro', models.ForeignKey(help_text='Referencia al libro prestado (FK)', on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='api.libro', verbose_name='Libro')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
            },
        ),
    ]
