# Generated by Django 6.1 on 2026-08-29 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lector',
            name='rut',
            field=models.CharField(blank=True, help_text='RUT o identificador de credencial del lector', max_length=20, null=True, verbose_name='RUT / Identificador'),
        ),
        migrations.AddField(
            model_name='lector',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Cuenta de usuario de Django asociada para inicio de sesión', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lector_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del Sistema'),
        ),
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(blank=True, default='', help_text='Breve resumen del libro', verbose_name='Sinopsis / Descripción'),
        ),
    ]
