# Generated by Django 6.1 on 2026-08-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lector_rut_lector_user_libro_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen referencial del libro subida desde el ordenador', null=True, upload_to='portadas/', verbose_name='Imagen de Portada'),
        ),
        migrations.AddField(
            model_name='libro',
            name='precio',
            field=models.DecimalField(decimal_places=0, default=9990, help_text='Precio de venta o valor de arriendo del libro', max_digits=10, verbose_name='Precio ($ CLP)'),
        ),
    ]
