"""
Django settings for biblioteca project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@*5b#-lur7f(ld11g%qc4=m*n(op-55nbkb$75&tc!-f0(g(8_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# -------------------------------------------------------------------------
# APLICACIONES INSTALADAS (INSTALLED_APPS)
# -------------------------------------------------------------------------
# Define qué módulos y paquetes forman parte del proyecto.
# Django cargará los modelos, migraciones, señales y rutas registrados aquí.
INSTALLED_APPS = [
    # Aplicaciones estándar predeterminadas de Django
    'django.contrib.admin',          # Panel de administración preconstruido
    'django.contrib.auth',           # Sistema de autenticación de usuarios y permisos
    'django.contrib.contenttypes',   # Sistema de tipos de contenido para asociar modelos
    'django.contrib.sessions',       # Gestión de sesiones de usuario
    'django.contrib.messages',       # Sistema de mensajes flash / notificaciones
    'django.contrib.staticfiles',    # Gestión y recolección de archivos estáticos (CSS, JS, imágenes)

    # Librerías de terceros
    'rest_framework',                # Django REST Framework: provee serializadores, vistas API, autenticación y endpoints REST

    # Aplicaciones locales del proyecto
    'api',                           # Aplicación principal de la API: contendrá nuestros modelos, serializadores, vistas y rutas
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'biblioteca.urls'

# -------------------------------------------------------------------------
# CONFIGURACIÓN DE PLANTILLAS (TEMPLATES)
# -------------------------------------------------------------------------
# Indica a Django los motores de renderizado y las rutas donde buscar archivos HTML.
# Al especificar os.path.join(BASE_DIR, 'templates'), Django buscará primero en
# el directorio global 'templates/' ubicado en la raíz del proyecto.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'biblioteca.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# -------------------------------------------------------------------------
# ARCHIVOS ESTÁTICOS (CSS, JavaScript, Imágenes)
# -------------------------------------------------------------------------
# - STATIC_URL: Prefijo de URL para servir archivos estáticos en el navegador.
# - STATICFILES_DIRS: Rutas absolutas adicionales donde Django buscará archivos
#   estáticos durante el desarrollo (nuestra carpeta 'static/' en la raíz).
# -------------------------------------------------------------------------
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# -------------------------------------------------------------------------
# ARCHIVOS MULTIMEDIA / CARGAS DE USUARIO (MEDIA)
# -------------------------------------------------------------------------
# Permite cargar y servir imágenes referenciales de portadas de libros desde el PC.
# -------------------------------------------------------------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
